### ISSUE TITLE
Settings Page!

### ISSUE THREAD

**Issue by AugustDG** [Megasix/follow_up_app#26]
**Is your feature request related to a problem? Please describe.**
A settings page to change all of the app settings

**Describe the solution you'd like**
Pretty much what it says on the box

**Describe alternatives you've considered**
There aren't many alternative to a settings page

**Additional context**
![image](https://user-images.githubusercontent.com/33916325/134773530-64e68ffb-ab63-446c-9662-b14a8f8c25e6.png)

**Comment by Megasix** [comment]
https://github.com/Megasix/follow_up_app/tree/main/lib/screens/mainMenu/settings, it is our actual page, we need to finish it though
